apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rest-api
spec:
  replicas: 3 # Set desired replicas for high availability
  selector:
    matchLabels:
      app: my-rest-api
  template:
    metadata:
      labels:
        app: my-rest-api
    spec:
      containers:
      - name: my-rest-api
        image: my-rest-api:latest # Replace with your image name
        ports:
        - containerPort: 5000
      livenessProbe: # Add livenessProbe for health checks
        httpGet:
          path: /
          port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        successThreshold: 1
        failureThreshold: 3
      readinessProbe: # Add readinessProbe for graceful startup
        httpGet:
          path: /
          port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        successThreshold: 1
        failureThreshold: 3

