apiVersion: v1
kind: Service
metadata:
  name: my-rest-api
spec:
  selector:
    app: my-rest-api
  type: LoadBalancer # Use LoadBalancer for external access
  ports:
  - port: 5000
    targetPort: 5000

